#!/usr/bin/env python3
"""
Generate a portable cut-plane viewer .scad for loose STLs — the file slice.py asks for
when handed more than one STL (it refuses to guess how separate meshes fit together).
Also accepts a SINGLE STL: emits the same `stl_assembly.scad` (one `_solid` + the inline
viewer, no posing), so the STL→parametric workflow has a stable `.scad` target that
run_batch/slice_viewer can drive (they need a `.scad`, not a raw STL) — same ceremony
whether the reference is one mesh or an assembly of several. For a PROJECT you do NOT
need this: the cut viewer is built into main.scad (the `[Inspect cut plane]` block) —
just open main.scad in the GUI.

From a set of STLs it writes `stl_assembly.scad`:
  - wraps each STL in a `<name>_solid()` with an editable pose (`<name>_pos` translate +
    `<name>_rot` rotate, under `[Hidden]`),
  - a top-level `assembly()` that unions them,
  - the cut viewer COPIED INLINE from cut_plane_viewer.scad, so the file is
    self-contained and portable (move it anywhere, even out of the repo).

You POSE the loose meshes by editing the vars — the pose lives in the file (the CLI
render slice.py runs reads them, not Customizer presets) — sweep `SHOW`/`CUT_POS` in the
Customizer to eyeball the fit, then slice:
    uv run tools/slice.py stl_assembly.scad z=0

Refuses to overwrite an existing output unless --force (it may hold hand-set poses).

Usage:
    uv run tools/make_assembly.py a.stl b.stl              # -> ./stl_assembly.scad
    uv run tools/make_assembly.py parts/*.stl -o asm.scad  # choose the output name
    uv run tools/make_assembly.py a.stl b.stl --stdout     # print, don't write
"""
from __future__ import annotations

import argparse
import math
import os
import re
import sys
from pathlib import Path

PAD_MM = 10          # CUT_POS slider headroom past the combined bbox
VIEWER = Path(__file__).resolve().parent.parent / "lib" / "cut_plane_viewer.scad"   # single source of the viewer


def inlined_viewer() -> str:
    """The viewer's module defs, copied VERBATIM from cut_plane_viewer.scad: from its
    first `module` to before the Self-preview line — one source, no 2nd copy."""
    txt = VIEWER.read_text()
    start = txt.index("\nmodule ") + 1
    end = txt.index("// ---------- Self-preview")
    return ("// ---- cut-plane viewer (copied from lib/cut_plane_viewer.scad; self-contained) ----\n"
            + txt[start:end].strip())


def module_name(stem: str, taken: set[str]) -> str:
    """A valid OpenSCAD identifier from an STL stem, suffixed `_solid` (so slice.py
    discovers it), de-duplicated against names already used."""
    base = re.sub(r"\W+", "_", stem).strip("_").lower() or "part"
    if base[0].isdigit():
        base = "p_" + base
    name = base
    i = 2
    while f"{name}_solid" in taken:
        name = f"{base}_{i}"
        i += 1
    taken.add(f"{name}_solid")
    return name


def stl_range(stls: list[Path]) -> tuple[int, int]:
    """Combined world bbox of the raw STLs → shared CUT_POS range (poses start at 0;
    widen by hand if you spread pieces far)."""
    import numpy as np
    import trimesh
    los, his = [], []
    for p in stls:
        try:
            m = trimesh.load(str(p), process=True)
            if not m.is_empty:
                los.append(m.bounds[0])
                his.append(m.bounds[1])
        except Exception:
            pass
    if not los:
        return -100, 100
    lo = float(np.min(np.vstack(los))) - PAD_MM
    hi = float(np.max(np.vstack(his))) + PAD_MM
    return int(math.floor(lo)), int(math.ceil(hi))


def build_scad(stls: list[Path], out_dir: Path, rng: tuple[int, int], fuse=False) -> str:
    taken: set[str] = set()
    pieces = [(p, module_name(p.stem, taken)) for p in stls]
    lo, hi = rng
    mode = ("ONE fused object (a single *_solid): slice/analyze treat the posed STLs as one"
            if fuse else
            "separate parts (one *_solid each): slice measures the gaps/fit between them")
    L = [
        "// stl_assembly.scad — pose several imported STLs, inspect the cuts, then slice.",
        f"// MODE: {mode}.",
        "// POSE: edit each piece's _pos (translate) / _rot (rotate) under [Hidden] below — the",
        "//       pose lives in the file (the CLI render slice.py runs reads these). They are",
        "//       under [Hidden] so the Customizer shows ONLY the cut plane, not 6 fields/piece.",
        "// INSPECT: open in OpenSCAD ▸ Window ▸ Customizer, set SHOW + sweep CUT_POS.",
        "// SLICE:  uv run tools/slice.py stl_assembly.scad z=0",
        "// GENERATED by tools/make_assembly.py — re-running overwrites your poses (--force).",
        "// Self-contained: no `use`/`include` — the cut viewer is copied inline at the bottom.",
        "",
        "/* [Cut plane] */",
        'CUT_AXIS = "x";   // [x, y, z]',
        f"CUT_POS  = 0;     // [{lo}:1:{hi}]",
        'SHOW     = "off"; // [off, plane, cut, slice]',
        "",
        "/* [Hidden] */",
        "// EDIT the poses here (hidden from the Customizer; the slice CLI reads them).",
    ]
    for _path, name in pieces:
        L += [
            f"{name}_pos = [0, 0, 0];   // translate [x, y, z] mm",
            f"{name}_rot = [0, 0, 0];   // rotate [x, y, z] deg",
        ]
    L += ["$fn = 32;", ""]

    def imp(path, name):
        rel = Path(os.path.relpath(path.resolve(), out_dir)).as_posix()
        return f"translate({name}_pos) rotate({name}_rot) import(\"{rel}\")"

    if fuse:                                     # ONE solid = the union of the posed imports
        L += ["module assembly_solid() {"]
        L += [f"    {imp(p, n)};" for p, n in pieces]
        L += ["}", "", inlined_viewer(), "",
              "// Default view: SHOW=off is the clean fused object; `use` hides this from slice.py.",
              "cut_plane_view(CUT_AXIS, CUT_POS, SHOW) assembly_solid();", ""]
    else:                                        # one *_solid per piece (separate parts)
        L += [f"module {n}_solid() {imp(p, n)};" for p, n in pieces]
        L += ["", "module assembly() {"]
        L += [f"    {n}_solid();" for _p, n in pieces]
        L += ["}", "", inlined_viewer(), "",
              "// Default view: SHOW=off is the clean assembly; `use` hides this from slice.py.",
              "cut_plane_view(CUT_AXIS, CUT_POS, SHOW) assembly();", ""]
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", type=Path,
                    help="STL file(s): ≥2 = mating parts you pose into place; "
                         "1 = a single reference (no posing — the centered mesh as-is)")
    ap.add_argument("-o", "--output", type=Path, default=Path("stl_assembly.scad"),
                    help="output .scad (default: ./stl_assembly.scad)")
    ap.add_argument("--fuse", action="store_true",
                    help="treat the STLs as ONE object: emit a single fused *_solid (union of "
                         "the posed imports) instead of one per piece — for a multi-body export, "
                         "not separate mating parts")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing output (it may hold hand-set poses)")
    ap.add_argument("--stdout", action="store_true",
                    help="print the generated file instead of writing it")
    args = ap.parse_args()

    scads = [p for p in args.inputs if p.suffix.lower() == ".scad"]
    if scads:
        sys.exit("not needed for a project: the cut viewer is already in its main.scad "
                 "([Inspect cut plane] block) — open it in the GUI. make_assembly is only for "
                 "loose STLs without a main.scad.")
    stls = [p for p in args.inputs if p.suffix.lower() == ".stl"]
    other = [p for p in args.inputs if p.suffix.lower() != ".stl"]
    if other:
        sys.exit(f"unsupported inputs: {', '.join(map(str, other))}")
    missing = [p for p in stls if not p.exists()]
    if missing:
        sys.exit(f"no such file: {', '.join(map(str, missing))}")
    if len(stls) < 1:
        sys.exit("make_assembly needs at least 1 STL")
    # 1 STL = a single reference (no posing): still emits stl_assembly.scad with one
    # *_solid + the inline cut viewer, so run_batch/slice_viewer (which need a .scad,
    # not a raw STL) can drive the batch/curation flow against a stable target —
    # the same ceremony as a multi-part assembly. ≥2 STL = pose the mating parts.

    out = args.output
    out_dir = out.resolve().parent
    rng = stl_range(stls)
    text = build_scad(stls, out_dir, rng, fuse=args.fuse)

    if args.stdout:
        sys.stdout.write(text)
        return
    if out.exists() and not args.force:
        sys.exit(f"{out} already exists — use --force to overwrite "
                 f"(it may hold hand-set poses)")
    out.write_text(text)
    print(f"wrote {out}  ({len(stls)} pieces; edit the poses in the file; "
          f"CUT_POS [{rng[0]}:1:{rng[1]}])")


if __name__ == "__main__":
    main()
